### ISSUE TITLE
doc: document go4.org's version policy

### ISSUE THREAD

**Issue by bradfitz** [camlistore/go4#23]
Document that go4.org has no global minimum-Go version policy and it's up to each package to decide.

/cc @mpl

**Comment by bradfitz** [comment]
Also, fix go4.org/sort's tests to not fail (or just skip) on Go 1.5 and under.

**Comment by mpl** [comment]
https://review.gerrithub.io/295467

**Comment by mpl** [comment]
https://review.gerrithub.io/295496
