### ISSUE TITLE
TLS connections to go4.org failing: cert problem?

### ISSUE THREAD

**Issue by asicspatrick** [camlistore/go4#24]
I'm unable to establish a `TLS` connection from my build host to `go4.org`. The failure is strange as I can establish connections from other hosts, but when examining the cert with `openssl s_client -connect go4.org:443` I can repeatably get SSL failures from every host I try.

This looks like a problem on the `go4.org` server side with either the cert itself or the TLS implementation on the web server. Maybe a wonky Let's Encrypt cert or a web server config options that's preventing the correct TLS implementation from being selected on connection?

**openssh test output (same on every host I've tested)**

        $ openssl s_client -connect go4.org:443
        CONNECTED(00000003)
        2538:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/ssl/s23_clnt.c:593:

**curl verbose output from build host** 

        $ curl --tlsv1.2 -m 5 -I -v https://go4.org/
        *   Trying 212.47.227.56...
        * Connected to go4.org (212.47.227.56) port 443 (#0)
        * Initializing NSS with certpath: sql:/etc/pki/nssdb
        *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
          CApath: none
        * Operation timed out after 0 milliseconds with 0 out of 0 bytes received
        * Closing connection 0
        curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**curl output with alternate build host**

        $ curl -m 5 -I -v https://go4.org
        Rebuilt URL to: https://go4.org/
        Trying 212.47.227.56…
        Connected to go4.org (212.47.227.56) port 443 (#0)
        Initializing NSS with certpath: sql:/etc/pki/nssdb
        CAfile: /etc/pki/tls/certs/ca-bundle.crt
        CApath: none
        ALPN, server accepted to use http/1.1
        SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        Server certificate:
        subject: CN=go4.org
        start date: Oct 07 16:19:00 2016 GMT
        expire date: Jan 05 16:19:00 2017 GMT
        common name: go4.org
        issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
        > HEAD / HTTP/1.1
        > Host: go4.org
        > User-Agent: curl/7.47.1
        > Accept: /

<dl>
<dt>build host</dt>
<dd>amzn-ami-hvm-2016.09.0.20160923-x86_64-gp2</dd>
<dd>us-west-2</dd>

<dt>Alternate test with same AMI in different zone</dt>
<dd>amzn-ami-hvm-2016.09.0.20160923-x86_64-gp2</dd>
<dd>us-west-1</dd>
</dl>

**Comment by tgulacsi** [comment]
Too old ssl libs?

asicspatrick <notifications@github.com> ezt írta (időpont: 2016. nov. 18.,
P 7:00):

**Comment by asicspatrick** [comment]
I expanded my test host case and got some more detail. Seems secure renegotiation is disabled, which may be causing some older clients to fail on connect.

        $ openssl s_client -connect go4.org:443
        CONNECTED(00000003)
        140495242401440:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:770:
        ---
        no peer certificate available
        ---
        No client certificate CA names sent
        ---
        SSL handshake has read 7 bytes and written 295 bytes
        ---
        New, (NONE), Cipher is (NONE)
        Secure Renegotiation IS NOT supported
        Compression: NONE
        Expansion: NONE
        ---

Same error with a different set of openssl libraries. This looks like a wonky Let's Encrypt cert to me. Maybe it's a bad match for the client side CA's available. I have no problems getting through the handshake and establishing connections with other Let's Encrypt certs so it doesn't appear to be an issue with the cert provider.

Would it be possible to get the current cert updated early to see if that's the source of the problem?

**Comment by hakamadare** [comment]
@tgulacsi the initial test system (Amazon Linux 2016.09) has OpenSSL 1.0.1k installed; the 1.0.1 branch is still supported upstream, that still seems pretty recent.

**Comment by mpl** [comment]
@asicspatrick there wouldn't be some sort of proxy in front of your client, not properly supporting ALPN and/or HTTP/2 ?

**Comment by mpl** [comment]
@asicspatrick Does

`openssl s_client -connect go4.org:443 -servername go4.org`

work for you?

**Comment by asicspatrick** [comment]
> not properly supporting ALPN and/or _HTTP/2_ ?

I was able to successfully test a request to `go4.org` using a client that doesn't support `HTTP/2`, so I don't think `HTTP/2` support is our problem.

        $ curl --http2 https://go4.org
        curl: (1) Unsupported protocol
        $ curl -v https://go4.org
        * Rebuilt URL to: https://go4.org/
        *   Trying 212.47.227.56...
        * Connected to go4.org (212.47.227.56) port 443 (#0)
        * TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        * Server certificate: go4.org
        * Server certificate: Let's Encrypt Authority X3
        * Server certificate: DST Root CA X3
        > GET / HTTP/1.1
        > Host: go4.org
        > User-Agent: curl/7.49.1
        > Accept: */*
        > 
        < HTTP/1.1 200 OK
        < Date: Mon, 21 Nov 2016 03:56:49 GMT
        < Content-Length: 663
        < Content-Type: text/html; charset=utf-8

And for, `ALPN` I was able to connect from the host that's having the problem to `google.com` which using `ALPN` to negotiate the protocol.

        $ curl -s -v -D - -o /dev/null https://google.com/
        *   Trying 172.217.3.206...
        * Connected to google.com (172.217.3.206) port 443 (#0)
        * Initializing NSS with certpath: sql:/etc/pki/nssdb
        *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
        CApath: none
        * ALPN, server accepted to use http/1.1
        * SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        * Server certificate:
        * 	subject: CN=*.google.com,O=Google Inc,L=Mountain View,ST=California,C=US
        * 	start date: Nov 10 15:45:53 2016 GMT
        * 	expire date: Feb 02 15:31:00 2017 GMT
        * 	common name: *.google.com
        * 	issuer: CN=Google Internet Authority G2,O=Google Inc,C=US
        > GET / HTTP/1.1
        > Host: google.com
        > User-Agent: curl/7.47.1
        > Accept: */*
        > 
        < HTTP/1.1 301 Moved Permanently

Connections are getting held up on the `ALPN` part, though. So maybe there's something in the `ALPN` implementation on `go4.org` that's causing a problem?

        $ curl -s -v -D - -o /dev/null https://go4.org/
        *   Trying 212.47.227.56...
        * Connected to go4.org (212.47.227.56) port 443 (#0)
        * Initializing NSS with certpath: sql:/etc/pki/nssdb
        *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
        CApath: none

        ... hanging here

I don't believe a problem with `ALPN` would be causing trouble for `openssl`, though. To me, that indicates something wonky with the cert itself. Could be tested by swapping out the current cert which needs to be renewed before January 8 anyway.

**Comment by mpl** [comment]
@asicspatrick Did you miss my latest reply, about SNI?

**Comment by asicspatrick** [comment]
Hi @mpl sorry, I didn't miss your comment about `SNI`. And thanks for following up today.

I did test but forgot to include my result yesterday.

        $ curl -v https://go4.org -servername go4.org
        * Rebuilt URL to: https://go4.org/
        *   Trying 212.47.227.56...
        * Connected to go4.org (212.47.227.56) port 443 (#0)
        * Initializing NSS with certpath: sql:/etc/pki/nssdb
        *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
        CApath: none
        ... hangs here

Same `curl` result as the test without the `-servername go4.org` option. `SNI` does not seem to be part of the problem.

**Comment by mpl** [comment]
@asicspatrick -servername is an openssl s_client option, and not a curl one (at least not in my curl version - 7.35.0), so I don't see why it would change anything when testing with curl.

**Comment by bradfitz** [comment]
Yes, go4.org requires SNI.

This works for me:

> openssl s_client -connect go4.org:443 -servername go4.org

And this fails for me, as expected:

> openssl s_client -connect go4.org:443 

It's not 2006 anymore. I think 10 years is long enough that it can be required.
