### ISSUE TITLE
https://go4.org/ is down??

### ISSUE THREAD

**Issue by DexterHD** [camlistore/go4#25]
Can't install packages form or open it in browser.
```
[WARN]  Unable to checkout go4.org/reflectutil
[WARN]  Error updating go4.org/reflectutil: Cannot detect VCS
```

**Comment by mpl** [comment]
thanks for the heads up.
In the meantime, you can of course get the packages from https://github.com/camlistore/go4 instead.

**Comment by DexterHD** [comment]
> In the meantime, you can of course get the packages from https://github.com/camlistore/go4 instead.
Thanks for advice, but I can't. :) I'm using glide (https://glide.sh/) package manager, and one of my vendor packages use `go4.org` repository. So I will wait.

**Comment by mpl** [comment]
I don't know how glide works, but I'd be surprised if you couldn't fix things by manually fetching the packages, and then fiddle around a bit.
But I'm guessing it's a minor hiccup that Brad can fix in a minute when he's awake, so if you can indeed wait for a bit, I think it should be fixed very soon.

**Comment by DexterHD** [comment]
Yes, I can wait, thanks for fast reaction.

> I don't know how glide works, but I'd be surprised if you couldn't fix things by manually fetching the packages, and then fiddle around a bit.

It works like classic dependency management systems like `npm` (for node.js) or `composer` (in PHP).
I just say `glide get github.com/somepackage` and it automatically download all dependencies of it package, from repositories that listed in source code of this package. Of course I can replace repo by change sources of vendor package in my `./vendor` folder but I think it's bad way.

**Comment by bradfitz** [comment]
Ugh, my credit card expiration date changed and the auto-billing failed and Scaleway.com locked that server.

I've updated the billing and paid, but the server is still locked. I filed a support ticket.

Sorry. :-(

**Comment by bradfitz** [comment]
Back up.

**Comment by zmagajna** [comment]
I think this issue should be reopened: 
`package go4.org/reflectutil: unrecognized import path "go4.org/reflectutil" g/reflectutil: unrecognized import path "go4.org/reflectutil" (https fetch: Get https://go4.org/reflectutil?go-get=1: dial tcp 212.47.227.56:443: getsockopt: connection refused)`

Also can't open it in browser.

**Comment by mpl** [comment]
@zmagajna no problem here either with go get -u or with https://go4.org in the browser either.

Do you confirm it was just a fluke for you as well, or are you still having problems?

**Comment by zmagajna** [comment]
@mpl Thanks for the response, just before you answer my question i found out that there is a problem with our DNS resolvent. When i try to go get from other network it works perfect.

**Comment by rickw** [comment]
This just started happening today, again. Is there anyway to force Glide to use the GitHub version of go4? I get the package both in go get and glide get with the GitHub url but glide still fails.

**Comment by rickw** [comment]
Did they just change today? Everything worked fine yesterday

**Comment by bradfitz** [comment]
Yes, they changed sometime in the past 24 hours. I forget when exactly.

**Comment by rickw** [comment]
well I've wiped out and re init'd glide and still the same issue

**Comment by mpl** [comment]
@rickw it should be at ~21:27 UTC yesterday to be a bit more precise. :-)

**Comment by bradfitz** [comment]
I don't use glide, so I can't help.

**Comment by rickw** [comment]
yeah it's a deep dependency so it's not in my control I'll have to check out other things thanks

**Comment by bradfitz** [comment]
Just find the go4.org git repo in your $GOPATH or in glide's workspace and nuke it and re-fetch. I know that's what I said before, but I don't think you got the right one.

**Comment by arvenil** [comment]
```
[ERROR] Update failed for go4.org: The Remote does not match the VCS endpoint
[ERROR] Failed to install: The Remote does not match the VCS endpoint
```
Everything I try ends up with the same error.

**Comment by bradfitz** [comment]
See my replies from above.

**Comment by arvenil** [comment]
Ok, I think in case of glide it was more complex. They use caching, `glide cc` to clear cache helped (and dropping `/vendor` but maybe it was not necessary). Thanks.
