### ISSUE TITLE
go4.org repo collides with go4.org/grpc

### ISSUE THREAD

**Issue by adg** [camlistore/go4#30]
If you do this

```
$ go get go4.org/grpc
$ go get go4.org/types
```

then the second command fails.

This is because `go get` doesn't support nested repositories, and it's not clear that this can or should work (there should be a corresponding issue for cmd/go; will file it). The workaround is to perform the commands in the opposite order.

**Comment by mpl** [comment]
Ah I understand, thanks.
that's unfortunate.

**Comment by mpl** [comment]
@bradfitz wouldn't it be enough to change

    content="go4.org/grpc

into

    content="go4.org

in the meta HTML returned by https://go4.org/grpc ?

I've never played with meta yet, so I'm going to test and see on a dummy repo.

**Comment by mpl** [comment]
ok, I think this would work:

1) merge https://github.com/go4org/grpc/pull/1

2) change the meta tag at https://go4.org/grpc

to:

    <meta name="go-import" content="go4.org git https://github.com/go4org/grpc">

WDYT?

**Comment by bradfitz** [comment]
I'd rather not move everything down a directory in my fork, as I'm trying to keep the git history and file layout roughly compatible (and comparable) with the official grpc-go upstream git repo. That's why I didn't just copy everything into go4's git repo, for instance.

If I'd known about this problem before, I wouldn't have gone this route and I might've used a subdomain of go4.org instead. Maybe I still should, even if `import "grpc.go4.org/grpc"` isn't as pretty of an import.

Still thinking. Ideas welcome.

**Comment by shurcooL** [comment]
> even if `import "grpc.go4.org/grpc"` isn't as pretty of an import.

Have you considered an `import "grpc.go4.org"` import path instead? Less stuttering. I'm not aware of a reason it wouldn't work; is there one?

You'd want https://grpc.go4.org?go-get=1 to serve:

```HTML
<meta name="go-import" content="grpc.go4.org git https://github.com/go4org/grpc">
```

**Comment by bradfitz** [comment]
> Have you considered an import "grpc.go4.org" import path instead? Less stuttering. I'm not aware of a reason it wouldn't work; is there one?

Interesting thought.

Are there examples of anybody else doing this?

The closest I can think of is "golang.org/x/oauth2" which is only interesting in that its package files are in the root of its git repo and not under a subdirectory.

But yeah, I can't think of why that wouldn't work.

**Comment by shurcooL** [comment]
> Are there examples of anybody else doing this?

What exactly are you referring to by "this"? Using the root of a domain as a custom import path of a Go package, or something else?

One example I can think off the top of my head is:

- [`goji.io`](https://godoc.org/goji.io)

(I'm aware of it from https://github.com/golang/go/issues/13506 and https://github.com/golang/gddo/issues/355.)

**Comment by bradfitz** [comment]
Yes, "this" == "root of a domain as a custom import path".

Super excited to hear that works. I'll set that up now.

Thanks!

**Comment by bradfitz** [comment]
Done.

Let me know if there are problems or parts I forgot.

Thanks!

**Comment by shurcooL** [comment]
> Super excited to hear that works.

It's one of the things I really appreciate about Go (and contribute fixes when needed): it's simple and has few unexpected edge cases. Vanity import paths are just schema-less URLs, and the path value "/" (i.e., domain root) is no more special than "/foo/bar", so it's nice that it works equally well as an import path. 😊

**Comment by shurcooL** [comment]
> This is because `go get` doesn't support nested repositories, and it's not clear that this can or should work (there should be a corresponding issue for cmd/go; will file it).

The situation with nested/overlapping repositories is interesting. @adg, did you file that cmd/go issue? What number is it? I'd like to follow it.

**Comment by bradfitz** [comment]
He didn't. Feel free to file one yourself?
